print("Exponential Program")
print("-------------------")
x=int(input("Enter the x value:"))
y=int(input("Enter the y value:"))
z=int(input("Enter the z value:"))
print("Result:")
p=((x*x)+(y*y)+(z*z))
print("P=",p)
q=((x*x*x)+(y*y)+z+20)
print("Q=",q)
r=((x*x)*y+(y*y)*z*10)
print("R=",r)
s=((x*x*x)*(y*y)*z+2*x*y*z+x*y*z)
print("S=",s)
